title: "A Continuous Improvement Journal"
baseurl: "http://mokagio.github.io/continuous-improvement-journal"

# "canonify" URLs to avoid issues with GitHub pages and relative resources
canonifyurls: true

languageCode: "en-us"

metaDataFormat: "yaml"
theme: "heather-hugo"

